default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: <%= ENV['LANSKY_API_DB_USER'] %>
  password: <%= ENV['LANSKY_API_DB_PASSWORD'] %>
  host: <%= ENV['LANSKY_DB_HOST'] %>

development:
  <<: *default
  database: lansky_development

test:
  <<: *default
  database: lansky_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: lansky_production
